### ISSUE TITLE
Breaks chat

### ISSUE THREAD

**Issue by GABRlEL** [KaminoCoding/FriendNamer#3]
Does not work at all, it just makes the chat invisible for me = I can not see what anyone (including me) writes in chat.
Modversion: v1.0.0
Minecraftversion: 1.8.9
If you want more details, feel free to message me.

**Comment by BitForger** [comment]
I need logs and screenshots if you can provide. Also explain in depth the usage case that this is happening in.

**Comment by GABRlEL** [comment]
Uploading a video in which I showcase my problem rn.

**Comment by GABRlEL** [comment]
https://youtu.be/P98eH_67DV0 oh and by the way, I dont know why my audio sounds like shit, sorry!

**Comment by BitForger** [comment]
Hmm odd. I haven't touched this in a while as you can tell. Let me see the forge and minecraft logs. Also, can you provide the config file as well. Those should have some hints for what's going wrong.

**Comment by GABRlEL** [comment]
http://pastebin.com/raw/x3qPthvz okay here you go, that is the config file

**Comment by GABRlEL** [comment]
And what log files do you need?

**Comment by GABRlEL** [comment]
Oh, and does it matter that I am running Minecraft in a different directory than .minecraft?

**Comment by BitForger** [comment]
> And what log files do you need?

It should be something like `latest.log` or `forge-0.log`. I don't remember the name off the top of my head.

> Oh, and does it matter that I am running Minecraft in a different directory than .minecraft?

I don't think so since I *should* have used correct coding practices and used relative paths..

**Comment by GABRlEL** [comment]
"I don't think so since I _should_ have used correct coding practices and used relative paths.."
 Well, I think you messed up, Unless this ( https://gyazo.com/6067d8e80985c09858387e8682136bbd ) is just a visual glitch.

"It should be something like latest.log or forge-0.log. I don't remember the name off the top of my head."
Here you go: http://pastebin.com/raw/TXRrdPcQ

**Comment by GABRlEL** [comment]
By the way, I am running Minecraft in E:\Windows 7.2\Minecraft\hypixelmc and not C:\Users\Gabriel\AppData\Roaming\.minecraft

**Comment by GABRlEL** [comment]
I changed the config to this if you wonder: http://pastebin.com/raw/puhETYuv
And also, I checked the "friendnamer.cfg" in the config folder, it saved properly to ...\Minecraft\hypixelmc, so this might just be a visual glitch.

**Comment by BitForger** [comment]
Okay. My IDE is being stupid now and I'm back at work right now, but I think I have an idea of what might be the problem since it seems to be the regex. I'll look at it when i'm done working but for the mean time, try running it on a normal minecraft path since that is how forge creates the file structure. I didn't set any of the paths so what it's grabbing is what minecraft wants it to be.

**Comment by GABRlEL** [comment]
I guess I have to change the config via Notepad++, http://pastebin.com/raw/VCu0V8dB , Game just crashed when I tried to enter the config screen

**Comment by GABRlEL** [comment]
You want me to show you what happens if I run it in .minecraft? Here you go: http://pastebin.com/raw/D3BvuvjT Same problem persists.

**Comment by BitForger** [comment]
Can you send me a screen shot of what the chat looks like when not using the mod?

**Comment by GABRlEL** [comment]
With, or without chat modifications? The only mod I used was FriendNamer in the .minecraft test btw

**Comment by BitForger** [comment]
Just without the FriendNamer. It doesn't matter which directory it's in I suppose. I just want to see how messages are being formatted.

**Comment by GABRlEL** [comment]
I will try it on my E:\ drive, as that is the drive I am going to use it for.

**Comment by GABRlEL** [comment]
Oh, and here is the chat: https://gyazo.com/09229da5bb3d72fda984632e464d5940
EDIT: Keep in mind that I was using Voidchat in that screenshot. So this might not be accurate if you want the vanilla chat, but that is the chat mod I currently use and would want to use the mod with.

**Comment by GABRlEL** [comment]
I will be back in an hour, I will continue responding then.
_(will delete this message later)_

**Comment by BitForger** [comment]
Ok. I just finished work.. I'm gonna try and get my dev env working and take a look

**Comment by BitForger** [comment]
Two steps forward, one step back. It doesn't crash anymore and, as far as I can tell works without breaking. I'm attaching the latest build for you to try. If it doesn't work please copy the whole `logs/latest.log` file and put it in markdown code tags
[friendNamer-1.8.9-1.0.0.3.jar.zip](https://github.com/KaminoCoding/FriendNamer/files/823220/friendNamer-1.8.9-1.0.0.3.jar.zip)

**Comment by GABRlEL** [comment]
Well, this is awkward, it doesnt break chat, it doesnt crash, but now it doesnt do what it is supposed to do.
`[13:21:28] [Client thread/INFO]: Setting user: *CENSORED*
[13:21:32] [Client thread/INFO]: LWJGL Version: 2.9.4
[13:21:36] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Batty's Coordinates PLUS Mod for Forge, FMLFileResourcePack:Better Horse Hud, FMLFileResourcePack:CPSMod, FMLFileResourcePack:Custom Backgrounds, FMLFileResourcePack:Friend Namer, FMLFileResourcePack:James090500's MinecraftCape & Elytra Mod Mod, FMLFileResourcePack:Orange's 1.7 Animations, FMLFileResourcePack:orangesimplemod, FMLFileResourcePack:Screenshot Uploader, FMLFileResourcePack:Vanilla Enhancements, faithful32pack.zip, Default
[13:21:38] [Sound Library Loader/INFO]: Starting up SoundSystem...
[13:21:38] [Thread-8/INFO]: Initializing LWJGL OpenAL
[13:21:38] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[13:21:38] [Thread-8/INFO]: OpenAL initialized.
[13:21:38] [Sound Library Loader/INFO]: Sound engine started
[13:21:44] [Client thread/INFO]: Created: 32x32 textures-atlas
[13:21:45] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Batty's Coordinates PLUS Mod for Forge, FMLFileResourcePack:Better Horse Hud, FMLFileResourcePack:CPSMod, FMLFileResourcePack:Custom Backgrounds, FMLFileResourcePack:Friend Namer, FMLFileResourcePack:James090500's MinecraftCape & Elytra Mod Mod, FMLFileResourcePack:Orange's 1.7 Animations, FMLFileResourcePack:orangesimplemod, FMLFileResourcePack:Screenshot Uploader, FMLFileResourcePack:Vanilla Enhancements, faithful32pack.zip, Default
[13:21:45] [Client thread/INFO]: SoundSystem shutting down...
[13:21:45] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[13:21:45] [Sound Library Loader/INFO]: Starting up SoundSystem...
[13:21:45] [Thread-10/INFO]: Initializing LWJGL OpenAL
[13:21:45] [Thread-10/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[13:21:45] [Thread-10/INFO]: OpenAL initialized.
[13:21:45] [Sound Library Loader/INFO]: Sound engine started
[13:21:49] [Client thread/INFO]: textures: dropping miplevel from 5 to 4, because of minimum power of two: 16
[13:21:49] [Client thread/INFO]: Created: 1024x1024 textures-atlas
[13:22:18] [Client thread/INFO]: Connecting to play.timolia.de., 25565
[13:22:39] [Client thread/INFO]: [CHAT] EinfachRushen: GG :) #LikedSkill
[13:22:40] [Client thread/INFO]: [CHAT] PBC88: servus
[13:23:00] [Client thread/INFO]: [CHAT] Champsing: wo bist du?HabeinenVirus
[13:23:21] [Client thread/INFO]: [CHAT] HuntingWulf: gg
[13:23:28] [Client thread/INFO]: [CHAT] FloJo_MC: ChazerPVP Hacckt
[13:23:31] [Client thread/WARN]: Unable to play unknown soundEvent: minecraft:step.anvil
[13:23:45] [Client thread/INFO]: [CHAT] FinalDriveMode: 1.8 ist so randim
[13:23:48] [Client thread/INFO]: [CHAT] soupnaz: ne haha
[13:23:57] [Client thread/INFO]: [CHAT] JukeBoy: gg
[13:24:06] [Client thread/INFO]: [CHAT] Enerdragon20: FinalDriveMode 1v1?
[13:24:14] [Client thread/INFO]: [CHAT] HabeinenVirus: hilfe
[13:24:22] [Client thread/INFO]: [CHAT] Enerdragon20: FinalDriveMode 1v1? kannst doch soupen
[13:24:29] [Client thread/INFO]: [CHAT] JukeBoy: GG
[13:24:49] [Client thread/INFO]: Stopping!
[13:24:49] [Client thread/INFO]: SoundSystem shutting down...
[13:24:49] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com`

**Comment by GABRlEL** [comment]
I tried some stuff with my config, tried other users than me, checked nametags but it doesnt seem to work.

**Comment by GABRlEL** [comment]
Oh and it states ingame that it is 1.0.0.2 instead of 1.0.0.3

**Comment by BitForger** [comment]
Okay! Theory confirmed! It's the regex I have matches for the way vanilla chat sends messages with the username between <>. I'll make one that looks for a word with a colon at the end and build it in. I work full-time so it should be done when I can work on it tonight.

**Comment by GABRlEL** [comment]
Hyped to see the working version! Thanks for working on the mod!

**Comment by BitForger** [comment]
Try this one out.. np, one of my pet peeves is mod makers who don't update/support their mods. I need to update this sometime soon. 
[friendNamer-1.8.9-1.0.0.4.jar.zip](https://github.com/KaminoCoding/FriendNamer/files/825995/friendNamer-1.8.9-1.0.0.4.jar.zip)

**Comment by GABRlEL** [comment]
Okay, it works in Singleplayer (and on Multiplayer without chat plugins I guess), but on a server I tried it on (play.timolia.de) and it didn't work there. I guess this is because the chat is formatted different on there.
On vanilla: <PBC88> Text
On play.timolia.de: §7PBC88§7: §rText 
Oh and here the log if you need it:
```
[18:02:47] [Client thread/INFO]: Setting user: *CENSORED*
[18:02:49] [Client thread/INFO]: LWJGL Version: 2.9.4
[18:02:52] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Batty's Coordinates PLUS Mod for Forge, FMLFileResourcePack:Better Horse Hud, FMLFileResourcePack:CPSMod, FMLFileResourcePack:Custom Backgrounds, FMLFileResourcePack:Friend Namer, FMLFileResourcePack:James090500's MinecraftCape & Elytra Mod Mod, FMLFileResourcePack:Orange's 1.7 Animations, FMLFileResourcePack:orangesimplemod, FMLFileResourcePack:Screenshot Uploader, FMLFileResourcePack:Vanilla Enhancements, faithful32pack.zip, Default
[18:02:53] [Sound Library Loader/INFO]: Starting up SoundSystem...
[18:02:53] [Thread-8/INFO]: Initializing LWJGL OpenAL
[18:02:53] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[18:02:53] [Thread-8/INFO]: OpenAL initialized.
[18:02:53] [Sound Library Loader/INFO]: Sound engine started
[18:02:57] [Client thread/INFO]: Created: 32x32 textures-atlas
[18:02:58] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Batty's Coordinates PLUS Mod for Forge, FMLFileResourcePack:Better Horse Hud, FMLFileResourcePack:CPSMod, FMLFileResourcePack:Custom Backgrounds, FMLFileResourcePack:Friend Namer, FMLFileResourcePack:James090500's MinecraftCape & Elytra Mod Mod, FMLFileResourcePack:Orange's 1.7 Animations, FMLFileResourcePack:orangesimplemod, FMLFileResourcePack:Screenshot Uploader, FMLFileResourcePack:Vanilla Enhancements, faithful32pack.zip, Default
[18:02:58] [Client thread/INFO]: SoundSystem shutting down...
[18:02:58] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[18:02:58] [Sound Library Loader/INFO]: Starting up SoundSystem...
[18:02:58] [Thread-10/INFO]: Initializing LWJGL OpenAL
[18:02:58] [Thread-10/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[18:02:58] [Thread-10/INFO]: OpenAL initialized.
[18:02:58] [Sound Library Loader/INFO]: Sound engine started
[18:03:01] [Client thread/INFO]: textures: dropping miplevel from 5 to 4, because of minimum power of two: 16
[18:03:01] [Client thread/INFO]: Created: 1024x1024 textures-atlas
[18:03:08] [Client thread/INFO]: Connecting to play.timolia.de., 25565
[18:03:40] [Client thread/INFO]: [CHAT] PBC88: test nochmal
[18:03:45] [Client thread/INFO]: [CHAT] zRustrix: Rank 10 :D
[18:03:48] [Client thread/INFO]: [CHAT] DarkPvPSpark: 12
[18:03:53] [Server thread/INFO]: Starting integrated minecraft server version 1.8.9
[18:03:53] [Server thread/INFO]: Generating keypair
[18:03:54] [Server thread/INFO]: Preparing start region for level 0
[18:03:54] [Server thread/INFO]: Changing view distance to 16, from 10
[18:03:55] [Server thread/INFO]: PBC88[*CENSORED*] logged in with entity id 4411 at (-158.30000001192093, 70.0, 259.3921940760195)
[18:03:55] [Server thread/INFO]: Gabriel joined the game
[18:03:56] [Server thread/INFO]: Saving and pausing game...
[18:03:56] [Server thread/INFO]: Saving chunks for level 'friend namer'/Overworld
[18:03:58] [Server thread/INFO]: Saving chunks for level 'friend namer'/Nether
[18:03:58] [Server thread/INFO]: Saving chunks for level 'friend namer'/The End
[18:03:59] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2813ms behind, skipping 56 tick(s)
[18:04:06] [Server thread/INFO]: <Gabriel> Okay
[18:04:06] [Client thread/INFO]: [CHAT] <Gabriel> Okay
[18:04:09] [Server thread/INFO]: <Gabriel> This works
[18:04:09] [Client thread/INFO]: [CHAT] <Gabriel> This works
[18:04:18] [Server thread/INFO]: <Gabriel> But only on Vanilla, atleast it seems like that
[18:04:18] [Client thread/INFO]: [CHAT] <Gabriel> But only on Vanilla, atleast it seems like that
[18:04:21] [Server thread/INFO]: Saving and pausing game...
[18:04:21] [Server thread/INFO]: Saving chunks for level 'friend namer'/Overworld
[18:04:27] [Server thread/INFO]: Saving chunks for level 'friend namer'/Nether
[18:04:27] [Server thread/INFO]: Saving chunks for level 'friend namer'/The End
[18:04:27] [Server thread/INFO]: Stopping server
[18:04:27] [Server thread/INFO]: Saving players
[18:04:27] [Server thread/INFO]: Saving worlds
[18:04:27] [Server thread/INFO]: Saving chunks for level 'friend namer'/Overworld
[18:04:28] [Server thread/INFO]: Saving chunks for level 'friend namer'/Nether
[18:04:28] [Server thread/INFO]: Saving chunks for level 'friend namer'/The End
[18:04:32] [Client thread/INFO]: Stopping!
[18:04:32] [Client thread/INFO]: SoundSystem shutting down...
[18:04:32] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
```

**Comment by BitForger** [comment]
Clarify without chat plugins? Without voidchat? 
Yeah leave it to server admins to change the way stuff is formatted... that makes your username colored right? darned server plugins... I'll look into getting that working tonight.

**Comment by GABRlEL** [comment]
Uploading video where I demonstrate it, also showing how it works in Labymod

**Comment by GABRlEL** [comment]
Also, it says this in console on servers:
(example is hypixel)
[20:23:31] [Client thread/INFO] [FML]: Received client chat! Checking against username config
[20:23:31] [Client thread/INFO] [FML]: ^(\w+:)|(\w+)
[20:23:31] [Client thread/INFO] [FML]: [MVP+] spyman08 hat die Lobby betreten!
[20:23:31] [Client thread/INFO] [FML]: Does match: true. Text is: null
[20:23:31] [Client thread/INFO]: [CHAT] [MVP+] spyman08 hat die Lobby betreten!
[20:23:32] [Client thread/INFO] [FML]: Received client chat! Checking against username config
[20:23:32] [Client thread/INFO] [FML]: ^(\w+:)|(\w+)
[20:23:32] [Client thread/INFO] [FML]: [MVP+] PBC88: hjey
[20:23:32] [Client thread/INFO] [FML]: Does match: true. Text is: null
[20:23:32] [Client thread/INFO]: [CHAT] [MVP+] PBC88: hjey

**Comment by GABRlEL** [comment]
You could possibly try to check for the usernames in the config in the entire chat, and replace them with their according nickname

**Comment by GABRlEL** [comment]
https://www.youtube.com/watch?v=yzYgA1r_gyI&feature=youtu.be Here you go, there is the video

**Comment by BitForger** [comment]
Yeah i did leave some verbose logging in.. hmmm... I'm gonna have to take a look at it again.. I wonder why.....

**Comment by BitForger** [comment]
Sorry this for taking so long to get back to you about this. Here is a build that might work.. tbh I haven't had much time to work on it since I work full-time and still attend school.
[friendNamer-1.8.9-1.0.0.5.jar.zip](https://github.com/KaminoCoding/FriendNamer/files/834560/friendNamer-1.8.9-1.0.0.5.jar.zip)

**Comment by GABRlEL** [comment]
No problem, still at school on my part, I do not notice any change.

**Comment by GABRlEL** [comment]
And, how is it going with the mod sofar?

**Comment by BitForger** [comment]
@GABRlEL I haven't had a chance to work on the project over the weekend. Homework... I'm looking at it now though

**Comment by BitForger** [comment]
Alrighty, I don't know why some things aren't matching so send me logs of the servers you want it working on so I can see how everything gets sent to the client. The little `§` character doesn't like to match for some reason.

**Comment by BitForger** [comment]
Here is the latest build I have. I can't guarantee that this works.
[friendNamer-1.8.9-1.0.0.13.jar.zip](https://github.com/KaminoCoding/FriendNamer/files/840172/friendNamer-1.8.9-1.0.0.13.jar.zip)

**Comment by GABRlEL** [comment]
Still doesnt work,
Servers:
mc.hypixel.net
thevace.net
gommehd.net
play.timolia.de
`[15:11:47] [Client thread/INFO]: Setting user: *censored*
[15:11:50] [Client thread/INFO]: LWJGL Version: 2.9.4
[15:11:53] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Batty's Coordinates PLUS Mod for Forge, FMLFileResourcePack:Better Horse Hud, FMLFileResourcePack:CPSMod, FMLFileResourcePack:Custom Backgrounds, FMLFileResourcePack:Friend Namer, FMLFileResourcePack:James090500's MinecraftCape & Elytra Mod Mod, FMLFileResourcePack:Orange's 1.7 Animations, FMLFileResourcePack:orangesimplemod, FMLFileResourcePack:Screenshot Uploader, FMLFileResourcePack:Vanilla Enhancements, faithful32pack.zip, haze, Default
[15:11:54] [Sound Library Loader/INFO]: Starting up SoundSystem...
[15:11:54] [Thread-8/INFO]: Initializing LWJGL OpenAL
[15:11:54] [Thread-8/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[15:11:55] [Thread-8/INFO]: OpenAL initialized.
[15:11:55] [Sound Library Loader/INFO]: Sound engine started
[15:12:02] [Client thread/INFO]: Created: 64x64 textures-atlas
[15:12:03] [Client thread/INFO]: Reloading ResourceManager: Default, FMLFileResourcePack:Forge Mod Loader, FMLFileResourcePack:Minecraft Forge, FMLFileResourcePack:Batty's Coordinates PLUS Mod for Forge, FMLFileResourcePack:Better Horse Hud, FMLFileResourcePack:CPSMod, FMLFileResourcePack:Custom Backgrounds, FMLFileResourcePack:Friend Namer, FMLFileResourcePack:James090500's MinecraftCape & Elytra Mod Mod, FMLFileResourcePack:Orange's 1.7 Animations, FMLFileResourcePack:orangesimplemod, FMLFileResourcePack:Screenshot Uploader, FMLFileResourcePack:Vanilla Enhancements, faithful32pack.zip, haze, Default
[15:12:03] [Client thread/INFO]: SoundSystem shutting down...
[15:12:03] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
[15:12:03] [Sound Library Loader/INFO]: Starting up SoundSystem...
[15:12:04] [Thread-10/INFO]: Initializing LWJGL OpenAL
[15:12:04] [Thread-10/INFO]: (The LWJGL binding of OpenAL.  For more information, see http://www.lwjgl.org)
[15:12:04] [Thread-10/INFO]: OpenAL initialized.
[15:12:04] [Sound Library Loader/INFO]: Sound engine started
[15:12:11] [Client thread/INFO]: textures: dropping miplevel from 6 to 4, because of minimum power of two: 16
[15:12:11] [Client thread/INFO]: Created: 4096x4096 textures-atlas
[15:13:21] [Client thread/INFO]: Connecting to eu.hypixel.net, 25565
[15:13:23] [Client thread/INFO]: [CHAT] A new OptiFine version is available: HD Ultra H7
[15:13:23] [Client thread/INFO]: [CHAT]                                      
[15:13:23] [Client thread/INFO]: [CHAT] [MVP+] PBC88 hat die Lobby betreten!
[15:13:23] [Client thread/INFO]: [CHAT]                          
[15:13:24] [Client thread/INFO]: [CHAT] -----------------------------------------------------
[15:13:24] [Client thread/INFO]: [CHAT] *~"~"~"~"~"~*
[15:13:24] [Client thread/INFO]: [CHAT] Willkommen auf Hypixel, viel Spaß!
[15:13:24] [Client thread/INFO]: [CHAT] Viel Spass! Schau mal bei mir vorbei:
[15:13:24] [Client thread/INFO]: [CHAT]  -GabrielPBC.de
[15:13:24] [Client thread/INFO]: [CHAT] *~"~"~"~"~"~*
[15:13:24] [Client thread/INFO]: [CHAT] -----------------------------------------------------
[15:13:24] [Client thread/INFO]: [CHAT] PBC88 joined.
[15:13:25] [Client thread/INFO]: [CHAT] [MVP+] acoo398 hat die Lobby betreten!
[15:13:28] [Client thread/INFO]: [CHAT] -----------------------------------------------------
[15:13:28] [Client thread/INFO]: [CHAT] Du bist in keiner Party und wurdest daher in den ALL channel gemoved!
[15:13:28] [Client thread/INFO]: [CHAT] -----------------------------------------------------
[15:13:30] [Client thread/INFO]: [CHAT] [MVP+] PBC88: hey
[15:13:37] [Client thread/INFO]: Connecting to eu-proxy.thevace.net., 25565
[15:13:38] [Client thread/INFO]: [CHAT] [Freunde] [+] Dein Freund PBC88 hat sich eingeloggt.
[15:13:40] [Client thread/INFO]: [CHAT] [VIP] PBC88: hey
[15:13:45] [Client thread/INFO]: Connecting to play.timolia.de., 25565
[15:13:55] [Client thread/INFO]: [CHAT] >>> PBC88
[15:13:55] [Client thread/INFO]: [CHAT] >>> bySletix
[15:13:55] [Client thread/INFO]: [CHAT] <<< Blv_ckzz
[15:13:56] [Client thread/INFO]: [CHAT] PBC88: hey
[15:14:01] [Client thread/INFO]: Connecting to play.gommehd.net., 25565
[15:14:02] [Client thread/INFO]: [CHAT] [Freunde] Aktuell ist nur qonnaJr online.
[15:14:02] [Chunk Batcher 0/WARN]: Biome ID is out of bounds: 245373, defaulting to 0 (Ocean)
[15:14:02] [Chunk Batcher 0/WARN]: Biome ID is out of bounds: 245373, defaulting to 0 (Ocean)
[15:14:02] [Chunk Batcher 0/WARN]: Biome ID is out of bounds: 108131, defaulting to 0 (Ocean)
[15:14:02] [Chunk Batcher 0/WARN]: Biome ID is out of bounds: 108131, defaulting to 0 (Ocean)
[15:14:02] [Chunk Batcher 0/WARN]: Biome ID is out of bounds: 108131, defaulting to 0 (Ocean)
[15:14:04] [Chunk Batcher 1/WARN]: Needed to grow BufferBuilder buffer: Old size 524288 bytes, new size 2621440 bytes.
[15:14:04] [Chunk Batcher 0/WARN]: Needed to grow BufferBuilder buffer: Old size 524288 bytes, new size 2621440 bytes.
[15:14:04] [Chunk Batcher 0/WARN]: Needed to grow BufferBuilder buffer: Old size 524288 bytes, new size 2621440 bytes.
[15:14:05] [Chunk Batcher 1/WARN]: Needed to grow BufferBuilder buffer: Old size 524288 bytes, new size 2621440 bytes.
[15:14:07] [Client thread/INFO]: [CHAT] Already connecting to this server!
[15:14:07] [Chunk Batcher 1/WARN]: Needed to grow BufferBuilder buffer: Old size 524288 bytes, new size 2621440 bytes.
[15:14:15] [Client thread/INFO]: [CHAT] » PBC88 hat das Spiel betreten
[15:14:15] [Client thread/INFO]: [CHAT] [TTT] Warten auf weitere Spieler
[15:14:16] [Client thread/INFO]: [CHAT] [xPBC] PBC88: hey
[15:14:28] [Client thread/INFO]: Stopping!
[15:14:28] [Client thread/INFO]: SoundSystem shutting down...
[15:14:28] [Client thread/WARN]: Author: Paul Lamb, www.paulscode.com
`

**Comment by BitForger** [comment]
Here is another attempt, as usual include logs if it doesn't work...
[friendNamer-1.8.9-1.0.0.14.jar.zip](https://github.com/KaminoCoding/FriendNamer/files/853613/friendNamer-1.8.9-1.0.0.14.jar.zip)

**Comment by GABRlEL** [comment]
I am going to test this soon, I dont have time right now, remind me if I dont do it in like 2-3 days

**Comment by BitForger** [comment]
@GABRlEL any results on the test?

**Comment by GABRlEL** [comment]
Nope, still doesn't work, it still spams that it found no match with this error:
`
[23:07:18] [Client thread/INFO]: [CHAT] Click to view the stats of your SkyWars game!
[23:07:23] [Client thread/INFO] [FML]: Received client chat! Checking against username config
[23:07:23] [Client thread/INFO] [FML]: (?<=§\d)(\w+)(?=§\w)|<(\w+)>|(\w+:)
[23:07:23] [Client thread/INFO] [FML]: [MVP+] yureadindis hat die Lobby betreten!
[23:07:23] [Client thread/WARN] [FML]: ****************************************
[23:07:23] [Client thread/WARN] [FML]: * Illegal match!
java.lang.IllegalStateException: No match found
[23:07:23] [Client thread/WARN] [FML]: *  at io.cyb3rwarri0r8.friendnamer.client.NamesEventHandler.onChatEvent(NamesEventHandler.java:85)
[23:07:23] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_22_NamesEventHandler_onChatEvent_ClientChatReceivedEvent.invoke(.dynamic)
[23:07:23] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
[23:07:23] [Client thread/WARN] [FML]: *  at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
[23:07:23] [Client thread/WARN] [FML]: *  at net.minecraftforge.event.ForgeEventFactory.onClientChat(ForgeEventFactory.java:272)
[23:07:23] [Client thread/WARN] [FML]: *  at net.minecraft.client.network.NetHandlerPlayClient.func_147251_a(NetHandlerPlayClient.java:753)...
[23:07:23] [Client thread/WARN] [FML]: ****************************************`
